dreamstone-mariadb:
  image: mariadb
  container_name: dreamstone-mariadb
  ports:
    - "3306:3306"
  volumes:
    - ./.mysqldata:/var/lib/mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_DATABASE=dreamstone
    - MYSQL_USER=dreamstone
    - MYSQL_PASSWORD=dreamstone
    - TZ=America/Sao_Paulo
